version: 2
updates:
  - package-ecosystem: "npm"  # Change to your package manager (e.g., pip, maven)
    directory: "/"  # Location of the package files
    schedule:
      interval: "daily"  # How often to check for updates
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
